### ISSUE TITLE
Guanzon App - Marketplace

### ISSUE THREAD

**Issue by mnv121** [mtcuison/G-Apps#102]
Guanzon App Opening
Delay Opening / Cannot open  possible loading ng Ads.
Order Detail -MP 
a#Cancel Order 
a.1#cannot cancel message box Client Information is not set 
b#Processing Online Payment / Gcash / Maya
b.1# kulang bayad / status ng payment ###need adding payment
b.2# PayMaya need refactor for Maya 
c# My Order > Order Detail > Items .
c.1# upon selecting items simple form lang nag aappear
d#Item Selection
d.1#my mga nasa list na 0 PHP
d.2#upon selecting item / Product description hnd makita ung mahahaba detail nahati
d.3#upon selecting item / detail for color variation
e# Market place Question 
e.1# database Mp_Questions Doesnt exist
@mikegarcia8748 
reference picture
![c1](https://user-images.githubusercontent.com/97944690/201617065-e6b9e62b-7920-4353-a013-8e4b8e3d8208.jpg)
![d 1](https://user-images.githubusercontent.com/97944690/201798843-6facbf76-b4af-4aa7-a05d-f15b71dd258a.jpg)

**Comment by mnv121** [comment]
November 19 compile 
b#Processing Online Payment / Gcash / Maya
b.1# kulang bayad / status ng payment ###need adding payment (ok)
b.2# PayMaya need refactor for Maya
b.3# Refresh for my Order's / need Re-login for new status.  . .
b.4#Processing status / meron  nakalagay na status is TO PAY.

**Comment by mnv121** [comment]
a.1#cannot cancel message box Client Information is not set
b#Processing Online Payment / Gcash / Maya
b.1# kulang bayad / status ng payment ###need adding payment (OK)
b.2# PayMaya need refactor for Maya
c# My Order > Order Detail > Items .
c.1# upon selecting items simple form lang nag aappear (OK)
d#Item Selection
d.1#my mga nasa list na 0 PHP
d.2#upon selecting item / Product description hnd makita ung mahahaba detail nahati
d.3#upon selecting item / detail for color variation (OK)
e# Market place Question
e.1# database Mp_Questions Doesnt exist ( FOR 240)

New(Last Saturday)  November 19 compile
b#Processing Online Payment / Gcash / Maya
b.3# Refresh for my Order's / need Re-login for new status. . .
b.4#Processing status / meron nakalagay na status is TO PAY.
c# My Order > Order Detail > Items .
c.2# Discount -5% appearing

New (11/21/22)  November 19 compile
b#Processing Online Payment / Gcash / Maya
 b.5# Computation ng to Deposit pay either 100 or 0 pesos 
 c# My Order > Order Detail > Items .
 c.2# Total Payment = selling price lng di nasama ung shipping fee. 
 c.3# Suggestion# Break down payment sa detail
 F.# Processing COD
 f.1# Order Reference No . 1010101010 (Dinappalitan)
  G# To Pay / Processing Tab.
  g.1# Cancelled order status nasa /TO Pay parin (COD Transaction) MX0122000005
  g.2# unpaid order will be automatically cancelled within 24 hrs (removed)

**Comment by mnv121** [comment]
**a.1#cannot cancel message box Client Information is not set(OK)**
b#Processing Online Payment / Gcash / Maya
**b.1# kulang bayad / status ng payment ###need adding payment (OK)**
b.2# PayMaya need refactor for Maya
c# My Order > Order Detail > Items .
c.1# upon selecting items simple form lang nag aappear **(OK)**
d#Item Selection
d.1#my mga nasa list na 0 PHP
**d.2#upon selecting item / Product description hnd makita ung mahahaba detail nahati (5.27inch display / 6.26inch **mobile)(OK)**
**d.3#upon selecting item / detail for color variation (OK)**
e# Market place Question
e.1# database Mp_Questions Doesnt exist ( FOR 240)

New(Last Saturday) November 19 compile
b#Processing Online Payment / Gcash / Maya
**b.3# Refresh for my Order's / need Re-login for new status. . .(OK)**
b.4#Processing status / meron nakalagay na status is TO PAY.
c# My Order > Order Detail > Items .
**c.2# Discount -5% appearing ### (OK)**

New (11/21/22) November 19 compile
b#Processing Online Payment / Gcash / Maya
b.5# Computation ng to Deposit pay either 100 or 0 pesos
c# My Order > Order Detail > Items .
**c.2# Total Payment = selling price lng di nasama ung shipping fee.(OK)**
**c.3# Suggestion# Break down payment sa detail(OK)**
c.4# Selling Price / nag iiba after check out.
F.# Processing COD
f.1# Order Reference No . 1010101010 (Dinappalitan)
G# To Pay / Processing Tab.
**g.1# Cancelled order status nasa /TO Pay parin (COD Transaction) MX0122000005(OK)**
g.2# unpaid order will be automatically cancelled within 24 hrs (removed)
H# To Shipped
h.1#Tracking No(walang laman) /after shipped or pickup by courier

New (11/22/22) November 22 compile
@mikegarcia8748
reference photo below

**Comment by mnv121** [comment]
**a.1#cannot cancel message box Client Information is not ### set(OK)
b.1# kulang bayad / status ng payment ###need adding payment (OK)
b.3# Refresh for my Order's / need Re-login for new status. . .(OK)
b.5# Computation ng to Deposit pay either 100 or 0 pesos (OK)
c# My Order > Order Detail > Items .
c.1# upon selecting items simple form lang nag aappear (OK)
c.2# Discount -5% appearing ### (OK)
c.2# Total Payment = selling price lng di nasama ung shipping fee.(OK)
c.3# Suggestion# Break down payment sa detail(OK)
c.4# Selling Price / nag iiba after check out.(OK)
d#Item Selection
d.1#my mga nasa list na 0 PHP(OK)
d.2#upon selecting item / Product description hnd makita ung mahahaba detail nahati (5.27inch display / 6.26inch mobile)(OK)
d.3#upon selecting item / detail for color variation (OK)
F.# Processing COD
f.1# Order Reference No . 1010101010 (Dinappalitan) (OK)
g.1# Cancelled order status nasa /TO Pay parin (COD Transaction) MX0122000005(OK)
g.2# COD nag aappear sa TO PAY(OK)
e# Market place Question
e.1# database Mp_Questions Doesnt exist ( FOR 240)(OK)
H# To Shipped
h.1#Tracking No(walang laman) /after shipped or pickup by courier (C/o) sir mac

OLD November 19 compile
b#Processing Online Payment / Gcash / Maya
b.2# PayMaya need refactor for Maya
b.4#Processing status / meron nakalagay na status is TO PAY.
G# To Pay / Processing Tab.
g.2# unpaid order will be automatically cancelled within 24 hrs (removed)
#*# suggestion change into ''Unpaid Order cannot be cancelled within 24 hrs''

@mikegarcia8748
reference photo below

**Comment by mikegarcia8748** [comment]
PayaMaya Refactored to 'Maya'

To Pay on Processing Orders remove

**unpaid order will be automatically cancelled within 24 hrs (removed)**
lahat ng orders na hindi nabayaran dapat automatically macancel ng system within 24 hrs
cancel order button sa app hindi na magagamit ni user para mag cancel once na cancelled na sa system ung unpaid order.

**Comment by mnv121** [comment]
All Concern OK.
