### ISSUE TITLE
Android Marketplace 11/29/22 compile

### ISSUE THREAD

**Issue by mnv121** [mtcuison/G-Apps#106]
@mikegarcia8748 
a...**Deliver Tag**

1. To Review Product Does'nt Exist

b....**To Pay / Processing Tag**

1. Tagged Payment   Incase of Insuffiecient Amount Paid /Or cancelled Payment due to Reference Payment(Additional Payment for Customer)
reference pic below

**Transaction no mx01220000077**
cancelled payment
![image](https://user-images.githubusercontent.com/97944690/204450846-3c5978e0-d42e-4fed-912b-e160394b0828.png)
![image](https://user-images.githubusercontent.com/97944690/204451202-d1f0d715-f21a-4915-846c-c32fae2a5f49.png)

**Transaction no mx01220000070**
insufficient payment
![image](https://user-images.githubusercontent.com/97944690/204451016-1c5fed21-9161-472c-8c97-f04028cb53a7.png)
![image](https://user-images.githubusercontent.com/97944690/204451186-2c94db87-b96d-43a4-b344-e96d81ee85f3.png)

**Comment by mikegarcia8748** [comment]
Concerns solve.

Solution: wrong data type use for fields required.

**Comment by mnv121** [comment]
added valditation on Marketplace Desktop for  value > 0 amount closed&posted / status 
cancelled return to pay = ok
