### ISSUE TITLE
Android Marketplace 12/03/22 compile .(240 Testing)

### ISSUE THREAD

**Issue by mnv121** [mtcuison/G-Apps#110]
Android Marketplace 12/03/22 compile
@mikegarcia8748 
### 
 **A Complete Detail Fill-Up**

>a.1# Barangay Search Field dimakapag search (wala ung choices) 
>a.2#  Extra Space for selection of Barangay (hindi na mascroll down)

### 
 **B Home>Selected Item **

>b.1# Specification Detail Cropted. ( putol ng kunti pag mahaba messsage)

reference picture's Below

### 
a.1/a.2###############################################
![317913876_1337776147062404_252685880571790993_n](https://user-images.githubusercontent.com/97944690/205427680-c2ebea76-55f3-43b7-aac8-6c44702073b4.jpg)
### 
a.1/a.2###############################################
![b1](https://user-images.githubusercontent.com/97944690/205427727-81bca43d-ff01-47be-8cda-5019ada2d643.jpg)
![b1a](https://user-images.githubusercontent.com/97944690/205427723-2f0e2992-b41a-4712-b34a-dd7e80ee8b24.jpg)

**Comment by mikegarcia8748** [comment]
ung pull request #111 andun narin ung fix ng ToPay, tapos nagdagdag ako ng Processing Payment na label sa Purchase Info at List ng Orders.

Ung issue #110 
1. Troubleshooting ng hindi lumalabas na Brgy list, balik lang sa home pag tapos click ulit ung account completion or restart app.
2. Adjusted na sa pull request #111 ung layout para maview ng bou
