### ISSUE TITLE
Guanzon Connect v.4.03.01 a Issues

### ISSUE THREAD

**Issue by johncarlostacruz** [mtcuison/G-Apps#166]
- [x] #167
![image](https://github.com/mtcuison/G-Apps/assets/23698764/c1aa4cac-98d7-47dd-a83f-710411aaacf8)

- [ ] Transaction new Customer NULL yung nagdidisplay hindi pangalan ni Client.
![image](https://github.com/mtcuison/G-Apps/assets/23698764/ac894646-1141-4480-8aa5-d2d62b88787f)

- [ ] Matagal ang bato ng Data sa convertion ng GCARD QR to Non chip. G_Card_Master field cDigitalx = '1' sa server pero sa Branch cDigitalx = '2'. 

- [ ] UI. paayos daw po yung logo ng guanzon 
![image](https://github.com/mtcuison/G-Apps/assets/23698764/b820204c-2c3b-4bda-8bca-b4aa0b5d5568)

- [ ] palagyan daw po ng mga image yung mga products.
![image](https://github.com/mtcuison/G-Apps/assets/23698764/9bbfb022-edab-4b0f-a279-ede6d755e8f4)

**Comment by mikegarcia8748** [comment]
regarding sa issue ng NULL na name sa G-Card, maaaring sa data ng branch at sa main server ung may conflict.

**Comment by mikegarcia8748** [comment]
ung first concern, tinanggal ko pansamantala ung Motorcycle na inavail ni customer.

**Comment by johncarlostacruz** [comment]
- [ ] As per seg ilalagay na sa Qr yung pangalan ng customer para mag appear sa may gcard ng new customer.
create user ibang message ang lumalabas.
>Transaction new Customer NULL yung nagdidisplay hindi pangalan ni Client.

- [ ] create user ibang message ang lumalabas na message. 
![image](https://github.com/mtcuison/G-Apps/assets/23698764/aa83ac85-a344-44a6-9efe-0c9b779c6fce)

**Comment by jeraldjohncv** [comment]
![image](https://github.com/mtcuison/G-Apps/assets/133741456/289e4022-9656-465b-bada-d43a4d4d1844)
as of October 10, 2023

- [ ] Upon converting to Digital

**Comment by jeraldjohncv** [comment]
![image](https://github.com/mtcuison/G-Apps/assets/133741456/def8acf5-3f2e-417e-9c02-17ed050ed7bd)

as of October 10, 2023

- [ ] Upon saving MC Sales, there's supposed to be a QR Code that will appear, and the client will scan it to his/her phone using the GConnect App.

- [ ] 
![image](https://github.com/mtcuison/G-Apps/assets/133741456/77f38e45-17c3-45fe-a4cb-b75f758c36d4)

**Comment by mtcuison** [comment]
> ![image](https://user-images.githubusercontent.com/133741456/274499014-def8acf5-3f2e-417e-9c02-17ed050ed7bd.png)
> 
> as of October 10, 2023
> 
> * [ ]  Upon saving MC Sales, there's supposed to be a QR Code that will appear, and the client will scan it to his/her phone using the GConnect App.

pakicheck kung ang laman nitong query sa data nya ay https://restgk.guanzongroup.com.ph/ at kung napiping. pag naping pakitry ulit.

SELECT * FROM `xxxOtherConfig` WHERE sConfigID = 'websvr' AND sProdctID = 'IntegSys';

**Comment by jeraldjohncv** [comment]
Project ID: GConnect 


as per Sir Mac, the GCARD TAB will going to remove to prevent the User from getting confused when installing the application and creating account.

- [ ] ![image](https://github.com/mtcuison/G-Apps/assets/133741456/509521e6-8802-4edf-930e-081c00bbe49b)
