### ISSUE TITLE
Review Rewards Notifications for Panalo

### ISSUE THREAD

**Issue by mtcuison** [mtcuison/G-Apps#175]
Please review retrieving of notifications and rewards for Panalo.

Panalo Tab

![Image](https://github.com/mtcuison/G-Apps/assets/77145878/0bf00c12-3cc0-4649-8917-26d17f1a9202)

  - [ ] Rebates
  - [ ] Non-Cash Rewards

Notification Tab

![Image](https://github.com/mtcuison/G-Apps/assets/77145878/2e321335-d13e-427e-8ad2-43ae50b6c3ee)

  - [x] Rebates
  - [x] Non-Cash Rewards
  - [x] Raffle Entry

**Comment by mis1946** [comment]
Created separate issue for testing of notification tab.

https://github.com/mtcuison/G-Apps/issues/177

Panalo reward displaying was confirmed as okay of developers. Mac will handle the creation of panalo rewards later on and will close this issue if okay.
