### ISSUE TITLE
Notification for testing

### ISSUE THREAD

**Issue by unclejo** [mtcuison/G-Apps#177]
All notifications will be handled by this class, which manages Guanzon Connect.

each type of notification has its own object which will handle extra data(if exists)
Objects are able to

 for testing
- [x] Validate User and notification recipient
- [x] Save Remote Message(Notification data receive from firebase)
- [x] Parse Type of notification
- [ ] Send response - test for read notification
- [x] Execute command if exist -  test for execute Send response notification
- [ ] Retrieve and Provide notifications being requested by UI

![notif33](https://github.com/mtcuison/G-Apps/assets/76188409/3a9f8ef8-74fb-436e-bc00-9251bf967b97)
![notif333](https://github.com/mtcuison/G-Apps/assets/76188409/cc47b3fb-8868-48d3-be39-e82bb779d9f2)

**Comment by mtcuison** [comment]
please inform Jonathan when testing to send notifications on the account that you are using.

**Comment by mtcuison** [comment]
APK location is https://restgk.guanzongroup.com.ph/apk/gConnect.apk
