### ISSUE TITLE
Guanzon Benta

### ISSUE THREAD

**Issue by unclejo** [mtcuison/G-Apps#178]
### Product Inquiry

- [ ] 1. **User Authentication:**
   - User logs in or creates an account if not registered.

- [ ] 2. **Product Inquiry Page:**
   - User accesses the product inquiry page.
   - User selects the desired motorcycle brand from the available options.

- [ ] 3. **Motorcycle Units Selection:**
   - Upon brand selection, the app displays all motorcycle units available for the selected brand.
   - User chooses a specific motorcycle unit for inquiry.

- [ ] 4. **Inquiry Page:**
   - User is directed to the inquiry page for the selected motorcycle unit.
   - Inquiry page displays:
     - Image of the selected motorcycle unit.
     - Variant/Color selection options.
     - Payment method selection:
       - Cash payment.
       - Installment payment.

- [ ] 5. **Customer Information Collection:**
   - After configuring payment options, user proceeds to collect customer information.
   - User provides:
     - Full name.
     - Birth date and birthplace.
     - Address and contact details.

- [ ] 6. **Saving Inquiry Entry:**
   - User saves the completed inquiry entry.

- [ ] 7. **View Inquiry Status:**
   - User can access a separate page to view the status of mc model payment details.

**Comment by johncarlostacruz** [comment]
**Guanzon Benta Concerns**

- [ ]   Customer Information Page
>accepting space in the name and address (Client_Master)
![image](https://github.com/mtcuison/G-Apps/assets/23698764/33efe8bb-3288-4129-8b39-3ae46e0b80cf)

- [ ]  Motorcycle Units Selection
>lumalabas yung calculation ng installment sa cash entry, hindi namomodify yung downpayment sa may instalment.
![image](https://github.com/mtcuison/G-Apps/assets/23698764/30b902fc-0761-40af-8307-86b5a6cf787c)
![image](https://github.com/mtcuison/G-Apps/assets/23698764/508f3716-f140-40a6-8d9e-93b2f038c375)

- [ ] View Inquiry Status
>wala ito sa app

- [ ] saving entry with same info 
>null lumalabas pag same name ang info sa ganado_online
![image](https://github.com/mtcuison/G-Apps/assets/23698764/92916d4d-c27c-49bd-a157-a3de911728c1)

**Comment by johncarlostacruz** [comment]
01/24/24
**Product inquiry Customer info page:**

- [ ] 1. Birth place &  town/Municpality - ung parameters may null sa dulo Alaminos city, Null. then pag diko pinili ung parameter liapt ko lang ng other field inaaccept niya..hindi niya binavalidate ung value

- [ ] 2. Mobile no - no validation din po ito. kulang nilagay ko

- [ ] 3. Submit button based on the upper info value. bigla nalang bumalik sa brand selection na page. no message or notification. nicheck ko din sa dbase wala din angsave..

@szirabanal

**Comment by jeitee** [comment]
1. Birth place & town/Municpality  upon testing working ung validation po nito kindly check again for the new compiled apk
 2. Mobile no - no validation nag add na ko validations which is kapag hindi nagstart sa "09" ang mobile number di nea tatangapin same with kung kulang ung input na mobile number
3. Submit button checking po ulit ito kasi upon test ko nagkakaganun ung app kapag hindi pa nea naimport lahat nung mga need import sa model, brands and price

@szirabanal  @johncarlostacruz
